services:
  backend_db:
    image: postgres:16.4-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: django_src/Dockerfile
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - static:/backend/static
    depends_on:
      - backend_db
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/backend/static
    depends_on:
      - backend
  bot:
    build:
      context: .
      dockerfile: bot_src/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
volumes:
  pg_data:
  static:
