services:
  backend_db:
    image: postgres:16.4-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: django_src/Dockerfile
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - backend_db
volumes:
  pg_data:
